import talib

# 定义K线形态元组列表：(形态代码, 中文名称, TA-Lib函数)
PATTERN_DEFINITIONS = [
    ('CDL2CROWS', '两只乌鸦', talib.CDL2CROWS),
    ('CDL3BLACKCROWS', '三只乌鸦', talib.CDL3BLACKCROWS),
    ('CDL3INSIDE', '三内升/降', talib.CDL3INSIDE),
    ('CDL3LINESTRIKE', '三线打击', talib.CDL3LINESTRIKE),
    ('CDL3OUTSIDE', '三外升/降', talib.CDL3OUTSIDE),
    ('CDL3STARSINSOUTH', '南方三星', talib.CDL3STARSINSOUTH),
    ('CDL3WHITESOLDIERS', '三个白兵', talib.CDL3WHITESOLDIERS),
    ('CDLABANDONEDBABY', '弃婴', talib.CDLABANDONEDBABY),
    ('CDLADVANCEBLOCK', '前进受阻', talib.CDLADVANCEBLOCK),
    ('CDLBELTHOLD', '捉腰带线', talib.CDLBELTHOLD),
    ('CDLBREAKAWAY', '脱离', talib.CDLBREAKAWAY),
    ('CDLCLOSINGMARUBOZU', '收盘缺影线', talib.CDLCLOSINGMARUBOZU),
    ('CDLCONCEALBABYSWALL', '藏婴吞没', talib.CDLCONCEALBABYSWALL),
    ('CDLCOUNTERATTACK', '反击线', talib.CDLCOUNTERATTACK),
    ('CDLDARKCLOUDCOVER', '乌云盖顶', talib.CDLDARKCLOUDCOVER),
    ('CDLDOJI', '十字星', talib.CDLDOJI),
    ('CDLDOJISTAR', '十字星', talib.CDLDOJISTAR),
    ('CDLDRAGONFLYDOJI', '蜻蜓十字', talib.CDLDRAGONFLYDOJI),
    ('CDLENGULFING', '吞噬模式', talib.CDLENGULFING),
    ('CDLEVENINGDOJISTAR', '黄昏十字星', talib.CDLEVENINGDOJISTAR),
    ('CDLEVENINGSTAR', '黄昏之星', talib.CDLEVENINGSTAR),
    ('CDLGAPSIDESIDEWHITE', '向上/向下跳空并列阳线', talib.CDLGAPSIDESIDEWHITE),
    ('CDLGRAVESTONEDOJI', '墓碑十字星', talib.CDLGRAVESTONEDOJI),
    ('CDLHAMMER', '锤头', talib.CDLHAMMER),
    ('CDLHANGINGMAN', '吊颈', talib.CDLHANGINGMAN),
    ('CDLHARAMI', '孕线', talib.CDLHARAMI),
    ('CDLHARAMICROSS', '十字孕线', talib.CDLHARAMICROSS),
    ('CDLHIGHWAVE', '长影线', talib.CDLHIGHWAVE),
    ('CDLHIKKAKE', '陷阱', talib.CDLHIKKAKE),
    ('CDLHIKKAKEMOD', '修正陷阱', talib.CDLHIKKAKEMOD),
    ('CDLHOMINGPIGEON', '归巢鸽', talib.CDLHOMINGPIGEON),
    ('CDLIDENTICAL3CROWS', '三乌鸦', talib.CDLIDENTICAL3CROWS),
    ('CDLINNECK', '颈内线', talib.CDLINNECK),
    ('CDLINVERTEDHAMMER', '倒锤头', talib.CDLINVERTEDHAMMER),
    ('CDLKICKING', '反冲', talib.CDLKICKING),
    ('CDLKICKINGBYLENGTH', '反冲 - 由较长的缺影线决定多/空', talib.CDLKICKINGBYLENGTH),
    ('CDLLADDERBOTTOM', '梯底', talib.CDLLADDERBOTTOM),
    ('CDLLONGLEGGEDDOJI', '长脚十字', talib.CDLLONGLEGGEDDOJI),
    ('CDLLONGLINE', '长蜡烛', talib.CDLLONGLINE),
    ('CDLMARUBOZU', '缺影线', talib.CDLMARUBOZU),
    ('CDLMATCHINGLOW', '相同低价', talib.CDLMATCHINGLOW),
    ('CDLMATHOLD', '马特 holde', talib.CDLMATHOLD),
    ('CDLMORNINGDOJISTAR', '早晨十字星', talib.CDLMORNINGDOJISTAR),
    ('CDLMORNINGSTAR', '早晨之星', talib.CDLMORNINGSTAR),
    ('CDLONNECK', '颈上线', talib.CDLONNECK),
    ('CDLPIERCING', '贯穿模式', talib.CDLPIERCING),
    ('CDLRICKSHAWMAN', '人力车', talib.CDLRICKSHAWMAN),
    ('CDLRISEFALL3METHODS', '上升/下降三法', talib.CDLRISEFALL3METHODS),
    ('CDLSEPARATINGLINES', '分离线', talib.CDLSEPARATINGLINES),
    ('CDLSHOOTINGSTAR', '射击之星', talib.CDLSHOOTINGSTAR),
    ('CDLSHORTLINE', '短蜡烛', talib.CDLSHORTLINE),
    ('CDLSPINNINGTOP', '纺锤线', talib.CDLSPINNINGTOP),
    ('CDLSTALLEDPATTERN', '停顿形态', talib.CDLSTALLEDPATTERN),
    ('CDLSTICKSANDWICH', 'stick sandwich', talib.CDLSTICKSANDWICH),
    ('CDLTAKURI', '探水杆（带长下影线的蜻蜓十字）', talib.CDLTAKURI),
    ('CDLTASUKIGAP', 'tasuki gap', talib.CDLTASUKIGAP),
    ('CDLTHRUSTING', '冲刺形态', talib.CDLTHRUSTING),
    ('CDLTRISTAR', '三星', talib.CDLTRISTAR),
    ('CDLUNIQUE3RIVER', '独特三川', talib.CDLUNIQUE3RIVER),
    ('CDLUPSIDEGAP2CROWS', '向上跳空两只乌鸦', talib.CDLUPSIDEGAP2CROWS),
    ('CDLXSIDEGAP3METHODS', '向上/向下跳空三法', talib.CDLXSIDEGAP3METHODS)
]

# 从元组列表构建所需的字典和列表
all_pattern_functions = {code: func for code, name, func in PATTERN_DEFINITIONS}
available_patterns = [code for code, name, func in PATTERN_DEFINITIONS]
pattern_chinese_names = {code: name for code, name, func in PATTERN_DEFINITIONS}
